import React from 'react';

export const legalFields=[
    {accessor:'Index',Header:'اندکس',type:'String',group:'Moshtarak'},
{accessor:'StudyArea',Header:'محدوده مطالعاتی',type:'Lookup',group:'Moshtarak'},
{accessor:'Plain',Header:'دشت',type:'Lookup',group:'Moshtarak'},
{accessor:'OwnerName',Header:'نام و نام خانوادگی مالک',type:'String',group:'Moshtarak'},
{accessor:'City',Header:'شهرستان',type:'Lookup',group:'Moshtarak'},
{accessor:'Village',Header:'روستا',type:'String',group:'Moshtarak'},
{accessor:'Subscribe',Header:'شماره اشتراک',type:'String',group:'Moshtarak'},
{accessor:'LicenseNumber',Header:'شماره پروانه بهره برداری/حفر/مجوزصادره',type:'String',group:'Moshtarak'},
{accessor:'LicenseDate',Header:'تاریخ پروانه بهره برداری/حفر/مجوزصادره',type:'DateTime',group:'Moshtarak'},
{accessor:'Longitude',Header:'طول جغرافیایی',type:'Decimal',group:'Moshtarak'},
{accessor:'Latitude',Header:'عرض جغرافیایی',type:'Decimal',group:'Moshtarak'},
{accessor:'Pipe',Header:'قطر لوله آبده قبلی',type:'Decimal',group:'Moshtarak'},
{accessor:'EnginePower',Header:'قدرت موتورقبلی',type:'Decimal',group:'Moshtarak'},
{accessor:'TypeLicense',Header:'نوع مجوز',type:'Select',group:'Moshtarak' ,Options:'پروانه بهره برداری ,پروانه حفر,مجوز صادره فرم 1'},
{accessor:'Cultivated',Header:'سطح زیر کشت',type:'Decimal',group:'Moshtarak'},
{accessor:'CultivateType',Header:'نوع کشت',type:'Select',group:'Moshtarak',Options:'زراعی ,باغی,  زراعی وباغی'},
{accessor:'Industry ',Header:'صنعت و خدمات',type:'String',group:'Moshtarak'},
{accessor:'Drinking',Header:'شرب',type:'Select',group:'Moshtarak',Options:'شهری , روستایی'},
{accessor:'DebiMojaz',Header:'آبدهی مجاز (لیتر بر ثانیه)',type:'Decimal',group:'Moshtarak'},
{accessor:'WorkHours',Header:'ساعت كاركرد ',type:'Decimal',group:'Moshtarak'},
{accessor:'ArtifactsType',Header:'نو ع منصوبات مجاز',type:'Select',group:'Moshtarak',Options:'دیزلی, برقی'},
{accessor:'DugMethod',Header:'روش حفر',type:'Select',group:'Moshtarak',Options:'دستی, دستگاهی'},
{accessor:'TypeWell',Header:'نوع چاه',type:'Select',group:'Moshtarak',Options:'حریمی, کمکی'},
{accessor:'Volume',Header:'حجم برداشت مجاز  سالانه(هزارمترمکعب)',type:'Decimal',group:'Moshtarak'},
{accessor:'Description',Header:'توضیحات',type:'String',group:'Moshtarak'},
{accessor:'CultivatedFalse',Header:'سطح زیر کشت غیر مجاز',type:'Decimal',group:'Ezafe'},
{accessor:'CultivateTypeFalse',Header:'نوع کشت غیر مجاز',type:'Select',group:'Ezafe',Options:'زراعی, باغی, زراعی وباغی'},
{accessor:'UseFalse',Header:'نوع مصرف  غیر مجاز',type:'Select',group:'Ezafe',Options:'صنعتی, کشاورزی, دامداری ,شرب, سایر'},
{accessor:'DebiPresent',Header:'آبدهي فعلي(لیتردرثانیه) ',type:'Decimal',group:'Ezafe'},
{accessor:'VolumePresent',Header:'حجم برداشت فعلي(هزارمتر مکعب)',type:'Decimal',group:'Ezafe'},
{accessor:'ChangeUse',Header:'تغییر نوع مصرف',type:'Select',group:'Ezafe',Options:'دارد, ندارد'},
{accessor:'UseTiny',Header:'ریز مصرف',type:'String',group:'Ezafe'},
{accessor:'Overdrawn',Header:'حجم اضافه برداشت',type:'Decimal',group:'Ezafe'},
{accessor:'TypeMeter',Header:'نوع کنتور',type:'Select',group:'AdamNasb',Options:'حجمی هوشمند, حجمی مکانیکی,هوشمند آب و برق,سایر'},
{accessor:'MeterCompany',Header:'نام شرکت سازنده يا پيمانکار',type:'String',group:'AdamNasb'},
{accessor:'DateInstallation',Header:'تاريخ نصب',type:'DateTime',group:'AdamNasb'},
{accessor:'ChargeMeter',Header:'شارژ',type:'Select',group:'AdamNasb',Options:'دارد,ندارد'},
{accessor:'NumberMeter',Header:'قرائت',type:'Decimal',group:'AdamNasb'},
{accessor:'PlaceMeter',Header:'محل تهیه کنتور',type:'Select',group:'AdamNasb',Options:'انبار, تبصره  8,هزینه متقاضی'},
{accessor:'Overdrawn',Header:'اضافه برداشت قبلي(هزار متر مکعب در سال)',type:'Decimal',group:'AdamNasb'},
{accessor:'Saving',Header:'صرفه جويي با نصب کنتور (هزار متر مکعب در سال)',type:'Decimal',group:'AdamNasb'},
{accessor:'PlumbMeter',Header:'پلمپ کنتور',type:'Select',group:'AdamNasb',Options:'دارد,ندارد'},
{accessor:'PipeNew',Header:'قطر لوله آبده جدید',type:'Decimal',group:'Mansubat'},
{accessor:'EnginePowerNew',Header:'قدرت موتور جدید',type:'Decimal',group:'Mansubat'},
{accessor:'VolumeSaving',Header:'مقادير حجم آب صرفه جویی شده',type:'Decimal',group:'Mansubat'},
{accessor:'TransferLine',Header:'طول خط انتقال آب',type:'Decimal',group:'EnteghalAb'},
{accessor:'FloorBreaker',Header:'میزان کف شکنی/عمق فعلی',type:'Decimal',group:'KafShekani'},
{accessor:'WaterSupply',Header:'آب فروشی',type:'Decimal',group:'AbForoushi'},
{accessor:'UserFalse',Header:'کاربری غیر مجاز',type:'Select',group:'TaghirKarbari',Options:'صنعتی, کشاورزی, دامداری ,شرب, سایر'},
{accessor:'EndDate',Header:'تاریخ اتمام مدت پروانه بهره برداری',type:'DateTime',group:'AdamTamdid'},
{accessor:'LongitudeViolation',Header:'طول جغرافیایی تخلف',type:'Decimal',group:'TaghirMahal'},
{accessor:'LatitudeViolation',Header:'عرض جغرافیایی تخلف',type:'Decimal',group:'TaghirMahal'},
{accessor:'VolumOfWell',Header:'حجم برداشت از چاه',type:'Decimal',group:'AbShirin'},
{accessor:'WasteWater',Header:'حجم پساب',type:'Decimal',group:'AbShirin'},
{accessor:'VolumeFiltration',Header:'حجم آب تصفیه شده',type:'Decimal',group:'AbShirin'}]

export const illegalFields=[
    {accessor:'Index',Header:'شماره پرونده',type:'String',group:'MoshtarakGhair'},
    {accessor:'StudyArea',Header:'محدوده مطالعاتی',type:'Lookup',group:'MoshtarakGhair'},
    {accessor:'Plain',Header:'دشت',type:'Lookup',group:'MoshtarakGhair'},
    {accessor:'OwnerName',Header:'نام و نام خانوادگی متخلف',type:'String',group:'MoshtarakGhair'},
    {accessor:'City',Header:'شهرستان',type:'Lookup',group:'MoshtarakGhair'},
    {accessor:'Village',Header:'روستا',type:'String',group:'MoshtarakGhair'},
    {accessor:'Longitude',Header:'طول جغرافیایی',type:'Decimal',group:'MoshtarakGhair'},
    {accessor:'Latitude',Header:'عرض جغرافیایی',type:'Decimal',group:'MoshtarakGhair'},
    {accessor:'DugDate',Header:'تاریخ حفر ',type:'DateTime',group:'MoshtarakGhair'},
    {accessor:'WorkHours',Header:'ساعت كاركرد ',type:'Decimal',group:'MoshtarakGhair'},
    {accessor:'Index',Header:'نوع مصرف ',type:'Select',group:'MoshtarakGhair',Options:'صنعتی, کشاورزی, دامداری ,شرب, سایر'},
    {accessor:'Index',Header:'تاریخ شروع بهره برداری',type:'DateTime',group:'MoshtarakGhair'},
    {accessor:'Index',Header:'آبدهی لحظه ای چاه (لیتردرثانیه)',type:'Decimal',group:'MoshtarakGhair'},
    {accessor:'Index',Header:'حجم آب صرفه جویی شده سالانه(هزارمتر مکعب)',type:'Decimal',group:'MoshtarakGhair'},
    {accessor:'Index',Header:'خسارت آبخوان',type:'Select',group:'MoshtarakGhair',Options:'اخذ شده, اخذ نشده'},
    {accessor:'Description',Header:'توضیحات',type:'String',group:'MoshtarakGhair'},
    {accessor:'SerialPlumb',Header:'شماه سریال پلمپ',type:'String',group:'Plumb'},
    {accessor:'years',Header:'سال حفر چاه',type:'Select',group:'Masloub',Options:'قبل 85 سال ,بعد سال85 '},
    {accessor:'UsePresent',Header:'میزان مصرف آب فعلی mcm',type:'Decimal',group:'Masloub'},
    {accessor:'WellDepthViolation',Header:'عمق چاه',type:'Decimal',group:'Masloub'},
    {accessor:'TypeWellViolation',Header:'نوع چاه',type:'Select',group:'Masloub',Options:'حریمی , کمکی'},
    {accessor:'WellPosition',Header:'وضعیت چاه',type:'Select',group:'Masloub',Options:'فعال ,غیر فعال'},
    {accessor:'EngineType',Header:'نوع موتور',type:'Select',group:'Masloub',Options:'دیزلی, برقی'},
    {accessor:'DateFull',Header:'تاریخ پر و مسلوب المنفعه نمودن چاه',type:'DateTime',group:'Masloub'},
    {accessor:'AnnualDischarge',Header:'تخلیه سالانه (هزار متر مکعب)',type:'Decimal',group:'Masloub'},
    {accessor:'HistoryBlocked',Header:'سابقه انسداد',type:'Select',group:'Masloub',Options:'دارد,ندارد'}]

  export const wellTypes=[{key:null,value:'انتخاب'},{key:'legal',value:'مجاز'},{key:'illegal',value:'غیر مجاز'}]
 
    export const infractionTypesLegal = [
    {
      name: 'آب فروشی',
      key: 'AbForoushi',
      label: 'آب فروشی',
    },
    {
      name: 'اضافه برداشت',
      key: 'Ezafe',
      label: 'اضافه برداشت',
    },
    {
      name: 'عدم نصب کنتور',
      key: 'AdamNasb',
      label: 'عدم نصب کنتور',
    },
    {
      name: 'منصوبات غیر مجاز',
      key: 'Mansubat',
      label: 'منصوبات غیر مجاز',
    },
    {
        name: 'انتقال آب',
        key: 'EnteghalAb',
        label: 'انتقال آب',
      },
      {
        name: 'کف شکنی',
        key: 'KafShekani',
        label: 'کف شکنی',
      },
      {
        name: 'تغییر کاربری',
        key: 'TaghirKarbari',
        label: 'تغییر کاربری',
      },
      {
        name: 'عدم تمدید پروانه',
        key: 'AdamTamdid',
        label: 'عدم تمدید پروانه',
      },
      {
        name: 'تغییر محل',
        key: 'TaghirMahal',
        label: 'تغییر محل',
      },
      {
        name: 'آب شیرین کن',
        key: 'AbShirin',
        label: 'آب شیرین کن',
      },
  ];
  export const infractionTypesIllegal = [
    
    {
      name: 'پلمپ چاههای غیر مجاز',
      key: 'Plumb',
      label: 'پلمپ چاههای غیر مجاز',
    },
    {
      name: 'پر و مسلوب المنفعه بودن چاههای غیر مجاز',
      key: 'Masloub',
      label: 'پر و مسلوب المنفعه بودن چاههای غیر مجاز',
    }
  ];